apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: three-tier-app
data:
  DB_HOST: "postgres.three-tier-app.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  # DB_PASSWORD should be a Secret, but for demo we keep here (NEVER in prod)
  # In production, use Kubernetes Secrets and Sealed Secrets / External Secrets.
  DB_PASSWORD: "supersecretpassword"