apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: backend
spec:
  replicas: 1                             # Optimized for single node memory footprint
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 379820351868.dkr.ecr.ap-south-1.amazonaws.com/backend:git-eec31d5
        ports:
        - containerPort: 4000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"