apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier-app
  labels:
    app: frontend
spec:
  replicas: 1                             # Optimized for single node memory
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 379820351868.dkr.ecr.ap-south-1.amazonaws.com/frontend:git-57138fe
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://backend.three-tier-app.svc.cluster.local:4000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"